### ISSUE TITLE
Preenchimento de conteudo da lista de musicas preferidas

### ISSUE THREAD

**Issue by williamiseki** [williamiseki/gcm-aula09_02#1]
cada membro do grupo devera preencher a pagina docs/musica.md com suas 4 musicas preferidas.

NÃO EDITEM A PAGINA NO BRANCH MASTER CRIEM UM NOVO BRANCH EDITE O ARQUIVO E CRIA UM PULL REQUEST

**Comment by fernandof1987** [comment]
Visto!
